#!/usr/bin/env python3
# openbao_traefik_cert.py
# Level 2: have OpenBao's PKI issue a TLS certificate and wire it into Traefik.
#
# WHAT IT DOES
#   1. Ensures OpenBao's PKI engine, a root CA, and an issuing role exist
#      (idempotent — safe to re-run).
#   2. Issues a leaf certificate for the given hostnames.
#   3. Writes cert.pem / key.pem into the Traefik dynamic directory.
#   4. Writes a Traefik dynamic TLS config (tls-openbao.yml) that serves that
#      cert as the default certificate — so Traefik presents an OpenBao-signed
#      cert instead of its built-in throwaway self-signed one.
#
# HONEST SCOPE NOTE
#   Steps 1-4 are verifiable in isolation and are unit-tested. Whether Traefik
#   then actually SERVES the cert can only be confirmed with the real proxy
#   stack running (docker compose up), which must be done on your machine — the
#   dev sandbox can't run the Traefik container. After running this, verify with:
#       curl -vk https://app.localhost 2>&1 | grep -i "issuer\|subject"
#   and you should see the OpenBao CA as the issuer.
#
# USAGE
#   OPENBAO_ADDR=... OPENBAO_TOKEN=... ./openbao_traefik_cert.py \
#       --hostnames app.localhost,keycloak.localhost,openbao.localhost \
#       --out-dir ./traefik/dynamic
#
#   Then restart/re-up Traefik so it loads the new dynamic TLS file.

from __future__ import annotations

import argparse
import os
import sys

import openbao_connect as ob


# The trailing block Traefik reads to serve our cert. `stores.default` +
# `certificates` makes this the DEFAULT cert Traefik presents on TLS routers
# that don't otherwise specify one. Written as a sibling dynamic file so it
# hot-reloads like the rest of traefik/dynamic.
_TRAEFIK_TLS_TEMPLATE = """\
# GENERATED by openbao_traefik_cert.py — do not edit by hand.
# Serves the OpenBao-issued certificate as Traefik's default TLS certificate.
tls:
  stores:
    default:
      defaultCertificate:
        certFile: {cert_path}
        keyFile: {key_path}
  certificates:
    - certFile: {cert_path}
      keyFile: {key_path}
"""


def ensure_pki(role: str, ca_common_name: str, allowed_domains: list) -> None:
    """Idempotently ensure the PKI engine, root CA, and issuing role exist."""
    ob.enable_pki_engine()
    # configure_pki_root_ca raises if a root already exists; that's fine on a
    # re-run — treat "already exists" as success so this stays idempotent.
    try:
        ob.configure_pki_root_ca(ca_common_name)
    except ob.OpenBaoError as exc:
        if "already" in str(exc).lower() or "existing" in str(exc).lower():
            print("  root CA already present — reusing")
        else:
            raise
    ob.create_pki_role(role, allowed_domains=allowed_domains)


def write_cert_files(cert_data: dict, out_dir: str) -> tuple[str, str]:
    """Write cert.pem (leaf + issuing CA) and key.pem into out_dir. Returns the
    two paths. The leaf is concatenated with the issuing CA so clients receive
    the full chain, and key.pem is written 0600."""
    os.makedirs(out_dir, exist_ok=True)
    cert_path = os.path.join(out_dir, "openbao-cert.pem")
    key_path = os.path.join(out_dir, "openbao-key.pem")

    leaf = cert_data["certificate"]
    issuing = cert_data.get("issuing_ca", "")
    chain = leaf if not issuing else (leaf.rstrip() + "\n" + issuing.rstrip() + "\n")

    # Write key first, locked down, THEN the cert — never leave a key world-readable.
    fd = os.open(key_path, os.O_WRONLY | os.O_CREAT | os.O_TRUNC, 0o600)
    with os.fdopen(fd, "w") as f:
        f.write(cert_data["private_key"].rstrip() + "\n")
    with open(cert_path, "w") as f:
        f.write(chain)
    return cert_path, key_path


def write_traefik_tls_config(out_dir: str, cert_container_path: str,
                             key_container_path: str) -> str:
    """Write the Traefik dynamic TLS file. The paths written are the paths as
    Traefik sees them INSIDE its container (the dynamic dir is mounted at
    /etc/traefik/dynamic), not the host paths."""
    config_path = os.path.join(out_dir, "tls-openbao.yml")
    with open(config_path, "w") as f:
        f.write(_TRAEFIK_TLS_TEMPLATE.format(
            cert_path=cert_container_path, key_path=key_container_path))
    return config_path


def main() -> int:
    p = argparse.ArgumentParser(description="Issue an OpenBao cert for Traefik.")
    p.add_argument("--hostnames",
                   default="app.localhost,keycloak.localhost,openbao.localhost",
                   help="Comma-separated hostnames for the cert (first is CN).")
    p.add_argument("--out-dir", default="./traefik/dynamic",
                   help="Where to write the cert files + Traefik TLS config.")
    p.add_argument("--role", default="traefik", help="PKI role name.")
    p.add_argument("--ca-cn", default="Auth Broker Internal Root CA",
                   help="Common name for the root CA.")
    p.add_argument("--ttl", default="720h", help="Leaf certificate TTL.")
    p.add_argument("--container-dynamic-dir", default="/etc/traefik/dynamic",
                   help="Path where Traefik sees the dynamic dir (its container "
                        "mount point) — used in the generated TLS config.")
    args = p.parse_args()

    if not os.environ.get("OPENBAO_TOKEN"):
        print("SKIP: set OPENBAO_ADDR and OPENBAO_TOKEN to issue a cert.")
        return 0

    hostnames = [h.strip() for h in args.hostnames.split(",") if h.strip()]
    if not hostnames:
        print("error: no hostnames given")
        return 1
    cn, alt_names = hostnames[0], hostnames

    print(f"Issuing OpenBao cert for {hostnames} (CN={cn})")
    ensure_pki(args.role, args.ca_cn, hostnames)
    cert_data = ob.issue_certificate(
        args.role, cn, alt_names=alt_names, ip_sans=["127.0.0.1"], ttl=args.ttl)

    cert_path, key_path = write_cert_files(cert_data, args.out_dir)
    print(f"  wrote {cert_path}")
    print(f"  wrote {key_path} (0600)")

    # The Traefik config must reference the cert by its IN-CONTAINER path.
    cont_cert = os.path.join(args.container_dynamic_dir,
                             os.path.basename(cert_path))
    cont_key = os.path.join(args.container_dynamic_dir,
                            os.path.basename(key_path))
    cfg = write_traefik_tls_config(args.out_dir, cont_cert, cont_key)
    print(f"  wrote {cfg}")
    print("\nDone. Restart Traefik (docker compose up -d --force-recreate "
          "traefik) so it loads the new cert, then verify:")
    print("  curl -vk https://app.localhost 2>&1 | grep -i 'issuer\\|subject'")
    return 0


if __name__ == "__main__":
    sys.exit(main())
