#!/usr/bin/env python3
# openbao_traefik_cert.py
# Level 2: have OpenBao's PKI issue a TLS certificate and wire it into Traefik.
#
# WHAT IT DOES
#   1. Ensures OpenBao's PKI engine, a root CA, and an issuing role exist
#      (idempotent — safe to re-run).
#   2. Issues a leaf certificate for the given hostnames.
#   3. Writes cert.pem / key.pem into the Traefik dynamic directory.
#   4. Writes a Traefik dynamic TLS config (tls-openbao.yml) that serves that
#      cert as the default certificate — so Traefik presents an OpenBao-signed
#      cert instead of its built-in throwaway self-signed one.
#
# HONEST SCOPE NOTE
#   Steps 1-4 are verifiable in isolation and are unit-tested. Whether Traefik
#   then actually SERVES the cert can only be confirmed with the real proxy
#   stack running (docker compose up), which must be done on your machine — the
#   dev sandbox can't run the Traefik container. After running this, verify with:
#       curl -vk https://app.localhost 2>&1 | grep -i "issuer\|subject"
#   and you should see the OpenBao CA as the issuer.
#
# USAGE
#   OPENBAO_ADDR=... OPENBAO_TOKEN=... ./openbao_traefik_cert.py \
#       --hostnames app.localhost,keycloak.localhost,openbao.localhost \
#       --out-dir ./traefik/dynamic
#
#   Then restart/re-up Traefik so it loads the new dynamic TLS file.

from __future__ import annotations

import argparse
import os
import sys

import openbao_connect as ob


# The trailing block Traefik reads to serve our cert. `stores.default` +
# `certificates` makes this the DEFAULT cert Traefik presents on TLS routers
# that don't otherwise specify one. Written as a sibling dynamic file so it
# hot-reloads like the rest of traefik/dynamic.
_TRAEFIK_TLS_TEMPLATE = """\
# GENERATED by openbao_traefik_cert.py — do not edit by hand.
# Serves the OpenBao-issued certificate as Traefik's default TLS certificate.
tls:
  stores:
    default:
      defaultCertificate:
        certFile: {cert_path}
        keyFile: {key_path}
  certificates:
    - certFile: {cert_path}
      keyFile: {key_path}
"""


def ensure_pki(role: str, ca_common_name: str, allowed_domains: list) -> None:
    """Idempotently ensure the PKI engine, root CA, and issuing role exist.

    configure_pki_root_ca is now genuinely idempotent (it checks for an existing
    CA and reuses it), so a re-run never mints a new root and orphans previously
    issued certs.
    """
    ob.enable_pki_engine()
    ob.configure_pki_root_ca(ca_common_name)
    ob.create_pki_role(role, allowed_domains=allowed_domains)


def write_cert_files(cert_data: dict, out_dir: str) -> tuple[str, str]:
    """Write cert.pem (leaf + issuing CA) and key.pem into out_dir. Returns the
    two paths. The leaf is concatenated with the issuing CA so clients receive
    the full chain, and key.pem is written 0600."""
    os.makedirs(out_dir, exist_ok=True)
    cert_path = os.path.join(out_dir, "openbao-cert.pem")
    key_path = os.path.join(out_dir, "openbao-key.pem")

    leaf = cert_data["certificate"]
    issuing = cert_data.get("issuing_ca", "")
    chain = leaf if not issuing else (leaf.rstrip() + "\n" + issuing.rstrip() + "\n")

    # Write key first, locked down, THEN the cert — never leave a key world-readable.
    fd = os.open(key_path, os.O_WRONLY | os.O_CREAT | os.O_TRUNC, 0o600)
    with os.fdopen(fd, "w") as f:
        f.write(cert_data["private_key"].rstrip() + "\n")
    with open(cert_path, "w") as f:
        f.write(chain)
    return cert_path, key_path


def write_traefik_tls_config(out_dir: str, cert_container_path: str,
                             key_container_path: str) -> str:
    """Write the Traefik dynamic TLS file. The paths written are the paths as
    Traefik sees them INSIDE its container (the dynamic dir is mounted at
    /etc/traefik/dynamic), not the host paths."""
    config_path = os.path.join(out_dir, "tls-openbao.yml")
    with open(config_path, "w") as f:
        f.write(_TRAEFIK_TLS_TEMPLATE.format(
            cert_path=cert_container_path, key_path=key_container_path))
    return config_path


def cert_needs_renewal(cert_path: str, *, renew_before_fraction: float = 0.33,
                       min_remaining_days: float = 7.0) -> bool:
    """Decide whether the cert at cert_path should be renewed.

    Renews when EITHER the remaining lifetime is below `renew_before_fraction`
    of the cert's total validity, OR fewer than `min_remaining_days` remain —
    whichever triggers first. A missing/unparseable cert also returns True (we
    should issue one). This is deliberately conservative: renewing early is
    harmless, running expired is not.
    """
    from datetime import datetime, timezone
    from cryptography import x509
    if not os.path.exists(cert_path):
        return True
    try:
        with open(cert_path, "rb") as f:
            data = f.read()
        # The file may be a chain (leaf first); parse the FIRST cert (the leaf).
        import re as _re
        blocks = _re.findall(
            rb"-----BEGIN CERTIFICATE-----.*?-----END CERTIFICATE-----",
            data, _re.DOTALL)
        if not blocks:
            return True
        leaf = x509.load_pem_x509_certificate(blocks[0])
    except Exception:  # noqa: BLE001 — unparseable => renew
        return True

    now = datetime.now(timezone.utc)
    not_before = leaf.not_valid_before_utc
    not_after = leaf.not_valid_after_utc
    if now >= not_after:
        return True  # already expired
    total = (not_after - not_before).total_seconds()
    remaining = (not_after - now).total_seconds()
    if total <= 0:
        return True
    if remaining < min_remaining_days * 86400:
        return True
    return (remaining / total) < renew_before_fraction


def renew_if_needed(role: str, hostnames: list, out_dir: str, *,
                    container_dynamic_dir: str = "/etc/traefik/dynamic",
                    ttl: str = "720h",
                    renew_before_fraction: float = 0.33,
                    min_remaining_days: float = 7.0,
                    force: bool = False) -> dict:
    """One-shot renewal check: re-issue the Traefik cert only if it's due.

    Designed to run on a schedule (cron/systemd timer) rather than as a daemon —
    a check-and-exit is simpler, safer, and testable. SAFETY: the NEW cert is
    issued and validated in memory BEFORE any file is overwritten, so a failed
    renewal (OpenBao down, role rejects) leaves the existing cert untouched and
    Traefik keeps serving it. Returns a small status dict.

    Assumes the PKI engine/CA/role already exist (run openbao_traefik_cert.py or
    ensure_pki first). Renewal only issues leaf certs; it never touches the CA.
    """
    cert_path = os.path.join(out_dir, "openbao-cert.pem")
    if not force and not cert_needs_renewal(
            cert_path, renew_before_fraction=renew_before_fraction,
            min_remaining_days=min_remaining_days):
        return {"renewed": False, "reason": "not due"}

    cn = hostnames[0]
    # Issue the new cert FIRST. If this raises, we return without touching the
    # existing files — the old cert stays in place.
    cert_data = ob.issue_certificate(
        role, cn, alt_names=hostnames, ip_sans=["127.0.0.1"], ttl=ttl)
    if not cert_data.get("certificate") or not cert_data.get("private_key"):
        return {"renewed": False, "reason": "issue returned no cert/key"}

    cert_p, key_p = write_cert_files(cert_data, out_dir)
    cont_cert = os.path.join(container_dynamic_dir, os.path.basename(cert_p))
    cont_key = os.path.join(container_dynamic_dir, os.path.basename(key_p))
    write_traefik_tls_config(out_dir, cont_cert, cont_key)
    return {"renewed": True, "serial": cert_data.get("serial_number", "?"),
            "cert_path": cert_p}


def main() -> int:
    p = argparse.ArgumentParser(description="Issue an OpenBao cert for Traefik.")
    p.add_argument("--hostnames",
                   default="app.localhost,keycloak.localhost,openbao.localhost,"
                           "app.test.local,keycloak.test.local,"
                           "openbao.test.local,traefik.test.local",
                   help="Comma-separated hostnames for the cert (first is CN).")
    p.add_argument("--out-dir", default="./traefik/dynamic",
                   help="Where to write the cert files + Traefik TLS config.")
    p.add_argument("--role", default="traefik", help="PKI role name.")
    p.add_argument("--ca-cn", default="Auth Broker Internal Root CA",
                   help="Common name for the root CA.")
    p.add_argument("--ttl", default="720h", help="Leaf certificate TTL.")
    p.add_argument("--container-dynamic-dir", default="/etc/traefik/dynamic",
                   help="Path where Traefik sees the dynamic dir (its container "
                        "mount point) — used in the generated TLS config.")
    p.add_argument("--renew", action="store_true",
                   help="Renewal mode: only re-issue if the existing cert is due "
                        "(safe to run on a cron/timer). Assumes PKI is set up.")
    args = p.parse_args()

    if not os.environ.get("OPENBAO_TOKEN"):
        print("SKIP: set OPENBAO_ADDR and OPENBAO_TOKEN to issue a cert.")
        return 0

    hostnames = [h.strip() for h in args.hostnames.split(",") if h.strip()]
    if not hostnames:
        print("error: no hostnames given")
        return 1

    # Renewal mode: check-and-maybe-reissue, don't touch the CA.
    if args.renew:
        result = renew_if_needed(
            args.role, hostnames, args.out_dir,
            container_dynamic_dir=args.container_dynamic_dir, ttl=args.ttl)
        if result.get("renewed"):
            print(f"Renewed cert (serial {result.get('serial')}). "
                  "Reload Traefik to pick it up.")
        else:
            print(f"No renewal needed ({result.get('reason')}).")
        return 0

    cn, alt_names = hostnames[0], hostnames

    print(f"Issuing OpenBao cert for {hostnames} (CN={cn})")
    ensure_pki(args.role, args.ca_cn, hostnames)
    cert_data = ob.issue_certificate(
        args.role, cn, alt_names=alt_names, ip_sans=["127.0.0.1"], ttl=args.ttl)

    cert_path, key_path = write_cert_files(cert_data, args.out_dir)
    print(f"  wrote {cert_path}")
    print(f"  wrote {key_path} (0600)")

    # The Traefik config must reference the cert by its IN-CONTAINER path.
    cont_cert = os.path.join(args.container_dynamic_dir,
                             os.path.basename(cert_path))
    cont_key = os.path.join(args.container_dynamic_dir,
                            os.path.basename(key_path))
    cfg = write_traefik_tls_config(args.out_dir, cont_cert, cont_key)
    print(f"  wrote {cfg}")
    print("\nDone. Restart Traefik (docker compose up -d --force-recreate "
          "traefik) so it loads the new cert, then verify:")
    print("  curl -vk https://app.localhost 2>&1 | grep -i 'issuer\\|subject'")
    return 0


if __name__ == "__main__":
    sys.exit(main())
