apiVersion: v1
kind: Service
metadata:
  name: auth-broker
  namespace: auth-broker
  labels:
    app: auth-broker
spec:
  type: ClusterIP
  selector:
    app: auth-broker
  ports:
    - name: http
      port: 8000
      targetPort: http
